common: &common
  working_directory: ~/heaven-blog
  docker:
    - image: circleci/ruby:2.3.7-node-browsers

version: 2
jobs:
  build:
    <<: *common
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      - run: |
          yarn global add grunt@1.0.4
          export PATH="$PATH:$(yarn global bin)"
          grunt release
      - save_cache:
          paths:
            - ./_site
          key: build-{{ .Environment.CIRCLE_SHA1 }}
  deploy:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
          - build-{{ .Environment.CIRCLE_SHA1 }}
      - run: |
          echo 'export COMMIT_SHA="$CIRCLE_SHA1"' >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "65:22:88:82:e5:50:30:a9:e3:15:d7:cc:7a:d4:5c:93"
      # check https://stackoverflow.com/questions/44773415/
      - run: |
          git checkout -b gh-pages origin/gh-pages
          cd _site && cp -r * ../
          cd ..
          git config credential.helper 'cache --timeout=120'
          git config user.email "<email>"
          git config user.name "CircleCI Bot"
          echo "rebuild for ${COMMIT_SHA}"
          git add .
          git commit --allow-empty -m "rebuild for ${COMMIT_SHA}"
          git push -q origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /gh-pages/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
